/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 3Davatar.glb -T 
Files: 3Davatar.glb [1.06MB] > /Users/hientran/Downloads/Git/PortfolioWebsite/frontend/public/model/3Davatar-transformed.glb [468.56KB] (56%)
*/

import React, { useEffect, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useAnimations, useFBX, useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function ThreeDModel(props) {
  const group = useRef();
  const { scene } = useGLTF('/model/3Davatar-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)

  const { animations: breakAnimations } = useFBX("/model/Breakdance Uprock Var 2.fbx");
  breakAnimations[0].name = "Break";

  const { animations: flairAnimations1 } = useFBX("/model/Flair1.fbx");
  flairAnimations1[0].name = "Flair1";

  const { animations: flairAnimations2 } = useFBX("/model/Flair2.fbx");
  flairAnimations2[0].name = "Flair2";

  const { animations: freezeAnimations } = useFBX("/model/Breakdance Freezes.fbx");
  freezeAnimations[0].name = "Freeze";

  const allAnimations = [...breakAnimations, ...flairAnimations1, ...flairAnimations2, ...freezeAnimations];
  const { actions } = useAnimations(allAnimations, group);

  useEffect(() => {
      if (!actions) return;

      const sequence = ["Break", "Flair1", "Flair2", "Freeze"];
      let index = 0;

      const playNext = () => {
        const current = actions[sequence[index]];
        if (!current) return;

        current.reset().fadeIn(0.5).play();

        const prevIndex = (index - 1 + sequence.length) % sequence.length;
        const prev = actions[sequence[prevIndex]];
        if (prev && prev !== current) prev.fadeOut(0.5);

        index = (index + 1) % sequence.length;
      };

      playNext();

      const interval = setInterval(playNext, 4500); // change every 5s
      return () => clearInterval(interval);
    }, [actions]);

  return (
    <group {...props} ref={group} dispose={null} rotation={[Math.PI, Math.PI, 0]}>
        <primitive object={nodes.Hips} />
        <skinnedMesh geometry={nodes['hair-60'].geometry} material={materials.M_Hair_60} skeleton={nodes['hair-60'].skeleton} />
        <skinnedMesh geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
        <skinnedMesh geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
        <skinnedMesh geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
        <skinnedMesh geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
        <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
        <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
        <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
        <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
    </group>
  )
}

useGLTF.preload('/model/3Davatar-transformed.glb')
